version: '3.8'
services:
  pointpillars:
    build: 
      context: .
      network: host
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - LIDAR_SOURCE=${LIDAR_SOURCE:-} # Default empty
    command: /opt/pointpillars/process_lidar ${LIDAR_SOURCE}
    volumes:
      - ./data:/workspace/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ulimits:
      memlock: -1
      stack: 67108864
